apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-app: elasticsearch-logging
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Values.cluster.binding_name }}
  namespace: {{ .Values.namespace.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ .Values.cluster.role_name }}
  apiGroup: ""

