apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    k8s-app: elasticsearch-logging
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  elasticsearch.yml: |-
    cluster:
      name: ${CLUSTER_NAME}
    node:
      master: ${NODE_MASTER}
      data: ${NODE_DATA}
      name: ${NODE_NAME}
      ingest: ${NODE_INGEST}
      max_local_storage_nodes: ${MAX_LOCAL_STORAGE_NODES}
    processors: ${PROCESSORS:1}
    network.host: 0.0.0.0
    
    http:
      enabled: ${HTTP_ENABLE}
    discovery:
      zen:
        ping.unicast.hosts: ${DISCOVERY_SERVICE}
    xpack.ml.enabled: false
