apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name_kibana }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  kibana.yml: |
    ---
    server.name: kibana
    server.host: "0"
    elasticsearch.url: http://elasticsearch:9200
