apiVersion: v1
kind: Service
metadata:
  labels:
    component: kibana
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Values.service_kibana.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service_kibana.port }}
    protocol: TCP
    targetPort: 5601
  selector:
    component: kibana
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service_kibana.type }}
