apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.logstash_deployment.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    k8s-app: logstash
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
     k8s-app: logstash
     app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        k8s-app: logstash
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: logstash
        image: "{{ .Values.image.repository_logstash }}:{{ .Values.image.tag_logstash }}"
        resources:
          limits:
            cpu: 0.1
          requests:
            cpu: 0.8
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/logstash/config/logstash.yml
          name: config
          subPath: logstash.yml
        - mountPath: /usr/share/logstash/pipeline/logstash.conf
          name: pipeline
          subPath: logstash.conf
      volumes:
      - name: config
        configMap:
          name: {{ .Values.configMap.name_logstash_config }}
          items:
          - key: logstash.yml
            path: logstash.yml
      - name: pipeline
        configMap:
          name: {{ .Values.configMap.name_logstash_pipeline }}
          items:
          - key: logstash.conf
            path: logstash.conf
