apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_master.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    component: elasticsearch
    role: {{ .Values.service_master.role }}
spec:
  ports:
    - port: {{ .Values.service_master.port }}
      protocol: TCP
      name: transport
  clusterIP: None
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: elasticsearch
    role: {{ .Values.service_master.role }}
