# Default values for helloworld-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

deployment:
  master_name: elasticsearch-master
  data_name: elasticsearch-data
  ingest_name: elasticsearch-ingest

image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: 6.4.3
  pullPolicy: IfNotPresent
  repository_kibana: docker.elastic.co/kibana/kibana-oss
  tag_kibana: 6.3.2

kibana_deployment:
  name: kibana

serviceAccount:
  name: elasticsearch-logging

service_master:
  name: elasticsearch-discovery
  port: 9300
  role: master

service_data:
  name: elasticsearch
  type: ClusterIP
  port: 9200
  role: data

service_ingest:
  name: elasticsearch-ingest
  type: ClusterIP
  port: 9200
  role: ingest

service_kibana:
  name: kibana
  type: LoadBalancer
  port: 5601

namespace: 
  name: monitoring

configMap:
  name: elasticsearch-config
  name_kibana: kibana-config