# Default values for helloworld-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
versions:
  - name: efs-elasticsearch-data
  - name: efs-elasticsearch-logging-usr
  - name: efs-elasticsearch-usr-datanode
  - name: efs-elasticsearch-usr-ingestnode
  - name: efs-elasticsearch-data-ingestnode
  - name: efs-elasticsearch-data-datanode

replicaCount: 1

deployment:
  master_name: elasticsearch-master
  data_name: elasticsearch-data
  ingest_name: elasticsearch-ingest

image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: 6.4.3
  pullPolicy: IfNotPresent
  repository_kibana: docker.elastic.co/kibana/kibana-oss
  tag_kibana: 6.3.2
  repository_logstash: docker.elastic.co/logstash/logstash
  tag_logstash: 6.5.4

cluster:
  role_name: elasticsearch-logging
  binding_name: elasticsearch-logging

kibana_deployment:
  name: kibana

logstash_deployment:
  name: logstash

serviceAccount:
  name: elasticsearch-logging

service_master:
  name: elasticsearch-discovery
  port: 9300
  role: master

service_data:
  name: elasticsearch
  type: ClusterIP
  port: 9200
  role: data

service_ingest:
  name: elasticsearch-ingest
  type: ClusterIP
  port: 9200
  role: ingest

service_kibana:
  name: kibana
  type: LoadBalancer
  port: 5601

namespace: 
  name: monitoring

configMap:
  name: elasticsearch-config
  name_kibana: kibana-config
  name_logstash_config: logstash-config
  name_logstash_pipeline: logstash-pipeline
