# Default values for helloworld-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: 6.4.3
  pullPolicy: IfNotPresent

serviceAccount:
  name: elasticsearch-logging

service_master:
  type: ClusterIP
  port: 9300
  role: master

namespace: 
  name: monitoring

configMap:
  name: elasticsearch-config